### ISSUE TITLE
It's running in local but when he tries to host it in AppService it showing below error.  bundle.js:2 

### ISSUE THREAD

**Issue by ddematheu2** [Azure-Samples/communication-services-javascript-quickstarts#108] opened 2023-03-24 17:51 UTC
communication-services-javascript-quickstarts/join-calling-to-teams-meeting at main · Azure-Samples/communication-services-javascript-quickstarts (github.com)

It's running in local but when he tries to host it in AppService it showing below error.

bundle.js:2 

       Uncaught SyntaxError: Invalid or unexpected token (at bundle.js:2:17413)

![d1ec6a25-de7e-4f4e-943f-ec24b746eb83](https://user-images.githubusercontent.com/43075365/227602400-09d7ae05-6785-4204-828f-92c5a19bf705.jpg)

and also the run syntax npx webpack-dev-server --entry ./client.js --output bundle.js --debug --devtool inline-source-map is not working with latest node version

**Comment by csandjon** [comment] 2023-06-14 19:50
Hello @ddematheu2, please provide us with the following information:
- [ ] Minimal steps to reproduce
- [ ] Log messages given by the failure

Thanks!

**Comment by palatter** [comment] 2023-07-25 20:55
We are closing this issue since we haven’t heard back from you for 10 days. Please feel free to reopen this issue if you have any questions.

**Closed by palatter** 2023-07-25 20:55 UTC
Labels: status:triage
